### ISSUE TITLE
Evaluate Reporting Tools for OpenSPP

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-base#44]
**Description**:
We are considering several options, including Metabase, Plotly Dash, and Superset. The objective is to choose a reporting tool that can efficiently generate reports within OpenSPP.

**Tasks**:
- [ ] Research the features and capabilities of Metabase.
- [ ] Research the features and capabilities of Plotly Dash. : https://plotly.com/dash/ 
- [ ] Research the features and capabilities of Superset.
- [ ] Evaluate how well each tool can be integrated into OpenSPP.
- [ ] Consider the feasibility of having reports generated within OpenSPP using each tool.
- [ ] Make a recommendation based on the evaluation.

**Comment by dasunhegoda** [comment]
Superset will be used.
